export const GALLERY_IMAGES = [
    {
        name: 'MosBuild 2025',
        header: 'Выставка MosBuild 2025 в Москве',
        images: [
            { src: '/gallery/mosbuild/1.jpg', alt: 'MosBuild 2025 — 1' },
            { src: '/gallery/mosbuild/2.jpg', alt: 'MosBuild 2025 — 2' },
            { src: '/gallery/mosbuild/3.jpg', alt: 'MosBuild 2025 — 3' },
            { src: '/gallery/mosbuild/4.jpg', alt: 'MosBuild 2025 — 4' },
            { src: '/gallery/mosbuild/5.jpg', alt: 'MosBuild 2025 — 5' },
        ],
    },
    {
        name: 'R+T 2024',
        header: 'Выставка R+T 2024',
        images: [
            { src: '/gallery/r+t/1.jpg', alt: 'R+T 2024 — 1' },
            { src: '/gallery/r+t/2.jpg', alt: 'R+T 2024 — 2' },
            { src: '/gallery/r+t/3.jpg', alt: 'R+T 2024 — 3' },
            { src: '/gallery/r+t/4.jpg', alt: 'R+T 2024 — 4' },
            { src: '/gallery/r+t/5.jpg', alt: 'R+T 2024 — 5' },
        ],
    },
    {
        name: 'KazBuild 2024',
        header: 'Выставка KazBuild 2024',
        images: [
            { src: '/gallery/kazbuild/1.jpg', alt: 'KazBuild 2024 — 1' },
            { src: '/gallery/kazbuild/2.jpg', alt: 'KazBuild 2024 — 2' },
            { src: '/gallery/kazbuild/3.jpg', alt: 'KazBuild 2024 — 3' },
            { src: '/gallery/kazbuild/4.jpg', alt: 'KazBuild 2024 — 4' },
            { src: '/gallery/kazbuild/5.jpg', alt: 'KazBuild 2024 — 5' },
            { src: '/gallery/kazbuild/6.jpg', alt: 'KazBuild 2024 — 6' },
            { src: '/gallery/kazbuild/7.jpg', alt: 'KazBuild 2024 — 7' },
            { src: '/gallery/kazbuild/8.jpg', alt: 'KazBuild 2024 — 8' },
            { src: '/gallery/kazbuild/9.jpg', alt: 'KazBuild 2024 — 9' },
            { src: '/gallery/kazbuild/10.jpg', alt: 'KazBuild 2024 — 10' },
            { src: '/gallery/kazbuild/11.jpg', alt: 'KazBuild 2024 — 11' },
            { src: '/gallery/kazbuild/12.jpg', alt: 'KazBuild 2024 — 12' },
            { src: '/gallery/kazbuild/13.jpg', alt: 'KazBuild 2024 — 13' },
        ],
    },
    {
        name: 'Batimat',
        header: 'Международная строительная выставка BATIMAT в Париже',
        images: [
            { src: '/gallery/batimat/1.jpg', alt: 'Batimat — 1' },
            { src: '/gallery/batimat/2.jpg', alt: 'Batimat — 2' },
            { src: '/gallery/batimat/3.jpg', alt: 'Batimat — 3' },
            { src: '/gallery/batimat/4.jpg', alt: 'Batimat — 4' },
            { src: '/gallery/batimat/5.jpg', alt: 'Batimat — 5' },
        ],
    },
    {
        name: 'BAU 2019',
        header: 'Выставка BAU 2019',
        images: [
            { src: '/gallery/bau/1.jpg', alt: 'BAU 2019 — 1' },
            { src: '/gallery/bau/2.jpg', alt: 'BAU 2019 — 2' },
            { src: '/gallery/bau/3.jpg', alt: 'BAU 2019 — 3' },
            { src: '/gallery/bau/4.jpg', alt: 'BAU 2019 — 4' },
            { src: '/gallery/bau/5.jpg', alt: 'BAU 2019 — 5' },
            { src: '/gallery/bau/6.jpg', alt: 'BAU 2019 — 6' },
            { src: '/gallery/bau/7.jpg', alt: 'BAU 2019 — 7' },
            { src: '/gallery/bau/8.jpg', alt: 'BAU 2019 — 8' },
            { src: '/gallery/bau/9.jpg', alt: 'BAU 2019 — 9' },
            { src: '/gallery/bau/10.jpg', alt: 'BAU 2019 — 10' },
            { src: '/gallery/bau/11.jpg', alt: 'BAU 2019 — 11' },
            { src: '/gallery/bau/12.jpg', alt: 'BAU 2019 — 12' },
        ],
    },
    {
        name: 'R+T 2018',
        header: 'Выставка R+T 2018',
        images: [
            { src: '/gallery/r+t2018/1.webp', alt: 'R+T 2018 — 1' },
            { src: '/gallery/r+t2018/2.webp', alt: 'R+T 2018 — 2' },
            { src: '/gallery/r+t2018/3.webp', alt: 'R+T 2018 — 3' },
            { src: '/gallery/r+t2018/4.webp', alt: 'R+T 2018 — 4' },
            { src: '/gallery/r+t2018/5.webp', alt: 'R+T 2018 — 5' },
            { src: '/gallery/r+t2018/6.webp', alt: 'R+T 2018 — 6' },
            { src: '/gallery/r+t2018/7.webp', alt: 'R+T 2018 — 7' },
            { src: '/gallery/r+t2018/8.webp', alt: 'R+T 2018 — 8' },
        ],
    },
    {
        name: 'Fit Show 2017',
        header: 'Выставка Fit Show 2017',
        images: [
            { src: '/gallery/fitshow/1.jpg', alt: 'Fit Show 2017 — 1' },
            { src: '/gallery/fitshow/2.jpg', alt: 'Fit Show 2017 — 2' },
            { src: '/gallery/fitshow/3.jpg', alt: 'Fit Show 2017 — 3' },
            { src: '/gallery/fitshow/4.jpg', alt: 'Fit Show 2017 — 4' },
            { src: '/gallery/fitshow/5.jpg', alt: 'Fit Show 2017 — 5' },
            { src: '/gallery/fitshow/6.jpg', alt: 'Fit Show 2017 — 6' },
            { src: '/gallery/fitshow/7.jpg', alt: 'Fit Show 2017 — 7' },
            { src: '/gallery/fitshow/8.webp', alt: 'Fit Show 2017 — 8' },
            { src: '/gallery/fitshow/9.webp', alt: 'Fit Show 2017 — 9' },
        ],
    },
];
